# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Addons for the management of multi company instances as well as
repo_name: Multi company modules
repo_slug: multi-company
repo_website: https://github.com/OCA/multi-company
travis_apt_packages: []
travis_apt_sources: []
