# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.17.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- product_tax_multicompany_default
- stock_intercompany
- purchase_sale_inter_company_stock_intercompany
repo_description: Addons for the management of multi company instances as well as
repo_name: Multi company modules
repo_slug: multi-company
repo_website: https://github.com/OCA/multi-company

